module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
        lg: '3rem',
        xl: '4rem',
        '2xl': '5rem',
      },
    },
    fontFamily: {
      manrope: ['Manrope', 'sans-serif'],
      montserrat: ['Montserrat', 'sans-serif'],
    },
    screens: {
      xs: '400px',
      sm: '540px',
      md: '720px',
      lg: '960px',
      xl: '1140px',
      '2xl': '1320px',
      '3xl': '1600px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#ffffff',
      purple: '#3f3cbb',
      midnight: '#121063',
      silver: '#ecebff',
      gray: '#dddddd',
      'bubble-gum': '#ff77e9',
      primary: '#3056D3',
      secondary: '#13C296',
      'body-color': '#637381',
      warning: '#F9C107',
      danger: '#DC3545',
      success: '#3CA745',
      info: '#3BA2B8',
      light: '#efefef',
      'form-stroke': '#E0E0E0',
      black: '#212B36',
      blue: '#2d20b7',
      lightblue: '#29166F',
      darkblue: '#29166F',
      green:'#0E9247',
      lightgreen:'#21D16D',
      'lightgreen-0': '#5FFCA3',
      red: '#F80605',
      darkred: '#BF1211',
      dark: {
        DEFAULT: '#090E34',
        700: '#090e34b3',
      },
    },
    extend: {
      backgroundImage: {
        'hero': "url('./assets/hero.jpg')",
      },      
    },
  },
  plugins: [],
}